services:
  timescaledb:
    image: ${TIMESCALE_IMAGE?-error}
    restart: always
    ports:
      - ${POSTGRES_PORT_HOST:-5432}:${POSTGRES_PORT_CONTAINER:-5432}
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-timescale}
      POSTGRES_USER: ${POSTGRES_USER:-timescale}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-error}
      POSTGRESS_PORT: ${POSTGRES_PORT_CONTAINER:-5432}
    volumes:
      - ./data:/var/lib/postgresql/data
  
  django-web:
    build: .
    container_name: django_soil_app
    ports:
    - ${DJANGO_PORT_HOST:-8000}:${DJANGO_PORT_CONTAINER:-8000}